### ISSUE TITLE
A feature to not download images but save images as links?

### ISSUE THREAD

**Issue by James-M-Robinson** [RaulS963/Rule34-Downloader#2]
Title says it but can there be a feature that saves the links rather than the images?

**Comment by RaulS963** [comment]
Yes, but I think such a feature will be better for the GUI version.

**Comment by James-M-Robinson** [comment]
I also thing the feature would be better for a GUI version! It would also be more convenient if the link was a direct link to the image like [https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png](url) 
this and not just a link to the webpage.

**Comment by RaulS963** [comment]
The current downloader stores the direct image-url (just like https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png) before downloading them, in a list (img_array). You can change the code (present in /py_code) a little bit to save only the links as a .txt or .csv file.
